### ISSUE TITLE
Error: cannot locate EFI partition for /

### ISSUE THREAD

**Issue by blackmailswitch** [chris1111/Drop-EFI-Big-Sur#1]
hi Chris,
I got this error - Error: cannot locate EFI partition for /
Big Sur 20B28 encrypted
![Screenshot 2020-11-11 at 15 08 26](https://user-images.githubusercontent.com/9391749/98815622-1ab48380-2430-11eb-9465-b435f8693e10.png)

**Comment by chris1111** [comment]
of course not working encrypted volume

**Comment by blackmailswitch** [comment]
or course?
its different than with Catalina?
Catalina encrypted was working

**Comment by chris1111** [comment]
> or course?
> its different than with Catalina?
> Catalina encrypted was working

Big Sur is totally diferant

**Comment by blackmailswitch** [comment]
okay.... interesting.
no workaround beside decrypt?

**Comment by chris1111** [comment]
Uninstall manually the V1 then use the new release V2
You have to uninstall manually because the V2 is different and after you can Uninstall or Install with the V2 anytime
https://github.com/chris1111/Drop-EFI-Big-Sur/releases/tag/V2
